model_options:
  test_size: 0.2
  random_state: 3
  features:
    - engines
    - passenger_capacity
    - crew
    - d_check_complete
    - moon_clearance_complete
    - iata_approved
    - company_rating
    - review_scores_rating

target:
  - tp                # Total precipitation

covariates:
  - u10               # 10-meter U wind component
  - v10               # 10-meter V wind component
  - d2m               # 2-meter dewpoint temperature
  - sst               # Sea surface temperature
  - sp                # Surface pressure
  - msl               # Mean sea level pressure
  - tcc               # Total cloud cover
  - tclw              # Total column cloud liquid water
  - tciw              # Total column cloud ice water
  - e                 # Evaporation
  - pev               # Potential evaporation
  - ro                # Runoff
  - z                 # Geopotential
  - si10              # 10-meter wind speed
  - lsm               # Land-sea mask
  - season            # Season (single temporal feature)


connectivity:
  method: distance
  threshold: 0.1
  knn: 8
  binary_weights: False
  include_self: False
  force_symmetric: True
  layout: csr

torch_dataset:
  method: distance
  horizon: 4
  window: 12
  stride: 1

datamodule:
  val_len: 0.1
  test_len: 0.2
  batch_size: 4
  workers: 15

model:
  hidden_size: 32
  emb_size: 32
  ff_size: 64
  n_layers: 3
  temporal_kernel_size: 3
  spatial_kernel_size: 3
  norm: layer
  gated: True

predictor:
  optim_class: torch.optim.Adam

training:
  max_epochs: 2
  log_every_n_steps: 2
  gradient_clip_val: 5
  precision: 16
